spring:
  application:
    name: LibraryApp
  datasource:
    url: jdbc:postgresql://postgres:5432/library_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  quartz:
    job-store-type: memory
    scheduler-name: FineScheduler
security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000

logging:
  level:
    org:
      springframework: DEBUG